// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Teste_Vize.Infraestrutura.Data;

#nullable disable

namespace Teste_Vize.Infraestrutura.Migrations
{
    [DbContext(typeof(DbContexto))]
    [Migration("20240604015346_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Teste_Vize.Dominio.Modelos.AcessoAPI", b =>
                {
                    b.Property<int>("AcessoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AcessoId"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("AcessoId");

                    b.ToTable("AcessoAPI");

                    b.HasData(
                        new
                        {
                            AcessoId = 1,
                            Login = "admin",
                            Senha = "admin"
                        });
                });

            modelBuilder.Entity("Teste_Vize.Dominio.Modelos.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Teclado Mecânico",
                            PrecoUnitario = 250.00m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Mouse Gamer",
                            PrecoUnitario = 150.00m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Formatação",
                            PrecoUnitario = 150.00m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Instalação de Hardware",
                            PrecoUnitario = 100.00m,
                            Tipo = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
